-- Initial database schema for the Internal Automation Platform.
-- This file is the canonical, human-readable source of truth for the
-- DDL.  The Alembic migration at alembic/versions/001_initial.py is
-- autogenerated from this file.  Keep the two in sync.

BEGIN;

-- ── users ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email         VARCHAR(255) NOT NULL UNIQUE,
    full_name     VARCHAR(200),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    sso_provider  VARCHAR(50),
    sso_subject   VARCHAR(255),
    password_hash VARCHAR(255),
    primary_role  VARCHAR(20) NOT NULL DEFAULT 'viewer'
        CHECK (primary_role IN ('admin','reviewer','operator','viewer')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_users_sso_subject ON users (sso_subject);

-- ── permissions + roles ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS permissions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS roles (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

-- ── sso_sessions ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sso_sessions (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_token_hash VARCHAR(128) NOT NULL UNIQUE,
    issued_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at         TIMESTAMPTZ NOT NULL,
    revoked_at         TIMESTAMPTZ,
    user_agent         VARCHAR(500),
    ip_address         VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS ix_sso_sessions_user ON sso_sessions (user_id);

-- ── templates ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS templates (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        VARCHAR(200) NOT NULL UNIQUE,
    description VARCHAR(1000),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS template_versions (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    template_id UUID NOT NULL REFERENCES templates(id) ON DELETE CASCADE,
    version     INTEGER NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('active','draft','archived')),
    payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_template_versions_template ON template_versions (template_id);
CREATE INDEX IF NOT EXISTS ix_template_versions_status ON template_versions (status);

-- ── ingested_rows ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ingested_rows (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id        VARCHAR(100) NOT NULL,
    source_row_hash  VARCHAR(64) NOT NULL,
    payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
    ingested_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ingested_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_ingested_rows_source ON ingested_rows (source_id);
CREATE INDEX IF NOT EXISTS ix_ingested_rows_hash ON ingested_rows (source_row_hash);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ingested_rows_source_hash
    ON ingested_rows (source_id, source_row_hash);

-- ── suggestions ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suggestions (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ingested_row_id  UUID NOT NULL REFERENCES ingested_rows(id) ON DELETE CASCADE,
    template_id      UUID NOT NULL REFERENCES templates(id) ON DELETE RESTRICT,
    confidence       DOUBLE PRECISION NOT NULL,
    state            VARCHAR(20) NOT NULL DEFAULT 'pending_review'
        CHECK (state IN ('pending_review','approved','rejected')),
    payload          JSONB NOT NULL DEFAULT '{}'::jsonb,
    reviewer_id      UUID REFERENCES users(id) ON DELETE SET NULL,
    review_notes     VARCHAR(2000),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at      TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_suggestions_state ON suggestions (state);
CREATE INDEX IF NOT EXISTS ix_suggestions_row ON suggestions (ingested_row_id);

-- ── audit_logs ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_logs (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    resource_type VARCHAR(100) NOT NULL,
    resource_id   VARCHAR(100) NOT NULL,
    action        VARCHAR(100) NOT NULL,
    actor_id      UUID REFERENCES users(id) ON DELETE SET NULL,
    before_state  JSONB NOT NULL DEFAULT '{}'::jsonb,
    after_state   JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_audit_resource ON audit_logs (resource_type, resource_id);
CREATE INDEX IF NOT EXISTS ix_audit_actor_time ON audit_logs (actor_id, occurred_at);
CREATE INDEX IF NOT EXISTS ix_audit_occurred ON audit_logs (occurred_at);

-- Reject UPDATE / DELETE on audit_logs to enforce immutability.
CREATE OR REPLACE FUNCTION audit_logs_no_mutate() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_logs is append-only';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS audit_logs_no_update ON audit_logs;
CREATE TRIGGER audit_logs_no_update
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION audit_logs_no_mutate();

COMMIT;